addSbtPlugin("com.geirsson"        % "sbt-scalafmt"          % "1.5.1")
addSbtPlugin("com.etsy"            % "sbt-checkstyle-plugin" % "3.1.1")
addSbtPlugin("com.github.sbt"      % "sbt-release"           % "1.1.0")
addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"         % "0.11.0")
addSbtPlugin("com.github.sbt"      % "sbt-native-packager"   % "1.9.16")